

services:
  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:16.2-alpine
    container_name: signasafe-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=signasafe
    volumes:
      - signasafe-volume:/var/lib/postgresql/data

  # Serviço da nossa API Spring Boot
  app:
    container_name: signasafe-app
    # Constrói a imagem a partir do Dockerfile na pasta atual (.)
    build: .
    ports:
      - "8080:8080"
    # Garante que o contêiner 'db' esteja pronto antes de iniciar a 'app'
    depends_on:
      - db
    # Passa as variáveis de ambiente para a nossa aplicação Spring Boot
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/signasafe
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      # Passa o segredo do JWT também como variável de ambiente (boa prática)
      - API_SECURITY_TOKEN_SECRET=meu-secret-super-secreto-para-o-projeto-signasafe
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
volumes:
  signasafe-volume: